#ifndef _ZIPCONSTANTS_H_
#define _ZIPCONSTANTS_H_

#define ZIPCONSTANTS_LOCSIG 0x04034b50
#define ZIPCONSTANTS_LOCHDR 30
#define ZIPCONSTANTS_LOCVER 4
#define ZIPCONSTANTS_LOCNAM 26

#define ZIPCONSTANTS_EXTSIG 0x08074b50
#define ZIPCONSTANTS_EXTHDR 16

#define ZIPCONSTANTS_CENSIG 0x02014b50
#define ZIPCONSTANTS_CENHDR 46
#define ZIPCONSTANTS_CENVER 6
#define ZIPCONSTANTS_CENNAM 28
#define ZIPCONSTANTS_CENOFF 42

#define ZIPCONSTANTS_ENDSIG 0x06054b50
#define ZIPCONSTANTS_ENDHDR 22
#define ZIPCONSTANTS_ENDTOT 10
#define ZIPCONSTANTS_ENDOFF 16

#define ZIPCONSTANTS_STORED 0
#define ZIPCONSTANTS_DEFLATED 8

#endif
